"""Add summary and description columns to User model

Revision ID: 54751e15608e
Revises: 
Create Date: 2024-11-09 05:43:35.563879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54751e15608e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
