"""Add additional fields to Job model

Revision ID: 905f983e184d
Revises: 405187e465d7
Create Date: 2024-11-09 11:54:11.777296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905f983e184d'
down_revision = '405187e465d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('2Model')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('description')
        batch_op.drop_column('company_size')
        batch_op.drop_column('company')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('company_size', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=150), nullable=True))

    op.create_table('2Model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('password', sa.VARCHAR(length=150), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('summary', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
