"""Reinitializing migration

Revision ID: 9512480d2672
Revises: 54751e15608e
Create Date: 2024-11-09 10:08:44.730844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9512480d2672'
down_revision = '54751e15608e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=False))
        batch_op.create_unique_constraint("uq_jobs_title", ['title'])  # Added a name for the constraint
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint("uq_jobs_title", type_='unique')  # Use the same name to drop the constraint
        batch_op.drop_column('title')
    # ### end Alembic commands ###
